CLOUDBEDS_BASE_API_URL='https://hotels.cloudbeds.com/api/v1.1'
CLIENT_ID='live1_1140_OYQNYIYM9Nilz4zOfoamYnHS'
CLIENT_SECRET='bVuueUiSEAxoxKjK4XjYL8uM6wyDahGZ'
TOKEN_VALID_TIME_IN_SECS=3000
PROPERTY_ID=1140