development:
  :product_name: "The Hostel Crowd CRM"
  :contact_email: "hello@thehostelcrowd.com"
  :title: "The Hostel Crowd CRM an online inventory management system."

test:
  :product_name: "The Hostel Crowd CRM"
  :contact_email: "hello@thehostelcrowd.com"
  :title: "The Hostel Crowd CRM an online inventory management system."
staging:
  :product_name: "The Hostel Crowd CRM"
  :contact_email: "hello@thehostelcrowd.com"
  :title: "The Hostel Crowd CRM an online inventory management system."
production:
  :product_name: "The Hostel Crowd CRM"
  :contact_email: "hello@thehostelcrowd.com"
  :title: "The Hostel Crowd CRM an online inventory management system."
